"""daily attendance submission

Revision ID: 2e5ffc16a44a
Revises: 6186b60fd1d6
Create Date: 2026-09-29 06:01:52.399948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5ffc16a44a'
down_revision: Union[str, Sequence[str], None] = '6186b60fd1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_attendance', sa.Column('submitted', sa.Boolean(), nullable=False))
    op.add_column('daily_attendance', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_attendance', sa.Column('submitted_by_user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'daily_attendance', 'users', ['submitted_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'daily_attendance', type_='foreignkey')
    op.drop_column('daily_attendance', 'submitted_by_user_id')
    op.drop_column('daily_attendance', 'submitted_at')
    op.drop_column('daily_attendance', 'submitted')
    # ### end Alembic commands ###
