"""daily attendance

Revision ID: 6186b60fd1d6
Revises: ce4b766034a4
Create Date: 2026-09-29 05:57:47.292607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6186b60fd1d6'
down_revision: Union[str, Sequence[str], None] = 'ce4b766034a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_session_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('marked_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'attendance_date', name='uq_daily_attendance_student_date')
    )
    op.create_index(op.f('ix_daily_attendance_academic_session_id'), 'daily_attendance', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_daily_attendance_attendance_date'), 'daily_attendance', ['attendance_date'], unique=False)
    op.create_index('ix_daily_attendance_campus_date', 'daily_attendance', ['campus_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_daily_attendance_campus_id'), 'daily_attendance', ['campus_id'], unique=False)
    op.create_index(op.f('ix_daily_attendance_grade_id'), 'daily_attendance', ['grade_id'], unique=False)
    op.create_index('ix_daily_attendance_section_date', 'daily_attendance', ['section_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_daily_attendance_section_id'), 'daily_attendance', ['section_id'], unique=False)
    op.create_index(op.f('ix_daily_attendance_student_id'), 'daily_attendance', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_attendance_student_id'), table_name='daily_attendance')
    op.drop_index(op.f('ix_daily_attendance_section_id'), table_name='daily_attendance')
    op.drop_index('ix_daily_attendance_section_date', table_name='daily_attendance')
    op.drop_index(op.f('ix_daily_attendance_grade_id'), table_name='daily_attendance')
    op.drop_index(op.f('ix_daily_attendance_campus_id'), table_name='daily_attendance')
    op.drop_index('ix_daily_attendance_campus_date', table_name='daily_attendance')
    op.drop_index(op.f('ix_daily_attendance_attendance_date'), table_name='daily_attendance')
    op.drop_index(op.f('ix_daily_attendance_academic_session_id'), table_name='daily_attendance')
    op.drop_table('daily_attendance')
    # ### end Alembic commands ###
