"""unique teacher email

Revision ID: ce4b766034a4
Revises: b29c7b50cf35
Create Date: 2026-09-29 04:23:09.214971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4b766034a4'
down_revision: Union[str, Sequence[str], None] = 'b29c7b50cf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    # ### end Alembic commands ###
